field.value.tzfield:
  type: field.value.string
  label: 'Default value'

field.field_settings.tzfield:
  label: 'Time zone settings'
  type: mapping
  mapping:
    exclude:
      type: sequence
      label: 'Excluded time zones'
      sequence:
        type: string
    default_site:
      type: boolean
      label: Use site's default time zone as default value
    default_user:
      type: boolean
      label: Use current user's time zone as default value

field.formatter.settings.tzfield_date:
  type: mapping
  label: 'Formatted current date field formatter settings'
  mapping:
    format:
      type: string
      label: 'Date format string'
